% Extract key quantitative findings from generated result files.
% The output is a plain-text report for drafting the Results section.

clear; clc;

reportFile = 'EAHE_key_findings.txt';
fid = fopen(reportFile, 'w');
if fid < 0
    error('Cannot open %s for writing.', reportFile);
end

cleanup = onCleanup(@() fclose(fid));

write_line(fid, 'EAHE Key Findings');
write_line(fid, '=================');
write_line(fid, '');

if exist('baseline_result.mat', 'file')
    S = load('baseline_result.mat', 'result');
    r = S.result;
    write_line(fid, 'Baseline case');
    if is_current_result(r)
        write_line(fid, sprintf('- Final outlet temperature: %.2f degC', r.Tout(end)));
        write_line(fid, sprintf('- Last-day mean heat transfer: %.1f W', r.degradation.Q_day_mean(end)));
        write_line(fid, sprintf('- Last-day heat-transfer degradation ratio: %.3f', r.degradation.eta_Q_day(end)));
        write_line(fid, sprintf('- Last-day near-pipe mean soil temperature rise: %.2f K', r.degradation.near_soil_rise_day_mean(end)));
    else
        write_line(fid, '- Skipped: baseline_result.mat was generated by an old model revision.');
    end
    write_line(fid, '');
end

write_csv_summary(fid, 'gap_sensitivity_summary.csv', 'gap_sensitivity_result.mat', 'Pipe-soil gap thickness sensitivity');
write_csv_summary(fid, 'gap_conductivity_sensitivity_summary.csv', 'gap_conductivity_sensitivity_result.mat', 'Gap effective thermal conductivity sensitivity');
write_csv_summary(fid, 'operation_mdot_summary.csv', 'operation_sensitivity_result.mat', 'Mass-flow-rate sensitivity');
write_csv_summary(fid, 'operation_length_summary.csv', 'operation_sensitivity_result.mat', 'Pipe-length sensitivity');
write_csv_summary(fid, 'soil_layer2_sensitivity_summary.csv', 'soil_layer2_sensitivity_result.mat', 'Layer-2 soil conductivity sensitivity');
write_csv_summary(fid, 'variable_gap_extension_summary.csv', 'variable_gap_extension_result.mat', 'Variable gap comparison');
write_csv_summary(fid, 'variable_gap_sensitivity_summary.csv', 'variable_gap_sensitivity_result.mat', 'Variable gap temperature-coefficient sensitivity');

fprintf('Key findings written to %s\n', reportFile);

function write_csv_summary(fid, csvFile, matFile, titleText)
    if ~exist(csvFile, 'file')
        return
    end
    if ~is_current_mat(matFile)
        write_line(fid, titleText);
        write_line(fid, repmat('-', 1, strlength(titleText)));
        write_line(fid, ['- Skipped: ', matFile, ' is missing or was generated by an old model revision.']);
        write_line(fid, '');
        return
    end
    T = readtable(csvFile);
    write_line(fid, titleText);
    write_line(fid, repmat('-', 1, strlength(titleText)));
    vars = T.Properties.VariableNames;
    for i = 1:height(T)
        parts = strings(1, numel(vars));
        for j = 1:numel(vars)
            value = T{i, j};
            if isnumeric(value)
                parts(j) = sprintf('%s=%.4g', vars{j}, value);
            elseif iscell(value)
                parts(j) = sprintf('%s=%s', vars{j}, string(value{1}));
            else
                parts(j) = sprintf('%s=%s', vars{j}, string(value));
            end
        end
        write_line(fid, ['- ', char(strjoin(parts, ', '))]);
    end
    write_line(fid, '');
end

function write_line(fid, text)
    fprintf(fid, '%s\n', text);
end

function tf = is_current_result(result)
    tf = isfield(result, 'param') ...
        && isfield(result.param, 'model_revision') ...
        && strcmp(result.param.model_revision, 'soil_phase_offset_v2');
end

function tf = is_current_mat(file)
    tf = false;
    if ~exist(file, 'file')
        return
    end
    try
        vars = whos('-file', file);
        names = {vars.name};
        if any(strcmp(names, 'result'))
            S = load(file, 'result');
            tf = is_current_result(S.result);
        elseif any(strcmp(names, 'results'))
            S = load(file, 'results');
            tf = iscell(S.results) && ~isempty(S.results) && is_current_result(S.results{1});
        elseif any(strcmp(names, 'case_gap'))
            S = load(file, 'case_gap');
            tf = is_current_result(S.case_gap);
        elseif any(strcmp(names, 'fixed_case'))
            S = load(file, 'fixed_case');
            tf = is_current_result(S.fixed_case);
        elseif any(strcmp(names, 'm_results'))
            S = load(file, 'm_results');
            tf = is_current_result_cell(S.m_results);
        elseif any(strcmp(names, 'L_results'))
            S = load(file, 'L_results');
            tf = is_current_result_cell(S.L_results);
        elseif any(strcmp(names, 'dt_results'))
            S = load(file, 'dt_results');
            tf = is_current_result_cell(S.dt_results);
        elseif any(strcmp(names, 'Nx_results'))
            S = load(file, 'Nx_results');
            tf = is_current_result_cell(S.Nx_results);
        elseif any(strcmp(names, 'Ntheta_results'))
            S = load(file, 'Ntheta_results');
            tf = is_current_result_cell(S.Ntheta_results);
        elseif any(strcmp(names, 'Nr_results'))
            S = load(file, 'Nr_results');
            tf = is_current_result_cell(S.Nr_results);
        end
    catch
        tf = false;
    end
end

function tf = is_current_result_cell(results)
    tf = iscell(results) && ~isempty(results) && is_current_result(results{1});
end
