% Plot near-pipe temperature contours from the baseline case.
% Run main_baseline first, or this script will run the baseline automatically.

clear; clc;

if exist('baseline_result.mat', 'file')
    load('baseline_result.mat', 'result');
    if ~is_current_result(result)
        error('baseline_result.mat was generated by an old model revision. Run main_baseline first.');
    end
else
    result = run_eahe_simulation();
    save('baseline_result.mat', 'result');
end

for k = 1:numel(result.snapshots.time)
    plot_temperature_contour(result, k, round(result.param.Nx_pipe / 2));
end

function tf = is_current_result(result)
    tf = isfield(result, 'param') ...
        && isfield(result.param, 'model_revision') ...
        && strcmp(result.param.model_revision, 'soil_phase_offset_v2');
end
