function postprocess_comsol_eahe(userCfg)
%POSTPROCESS_COMSOL_EAHE Postprocess COMSOL EAHE air-gap validation CSV files.
%
% The script reads COMSOL_EAHE_outputs/*.csv generated by
% comsol_eahe_airgap_model.m. It computes validation metrics, energy summaries,
% interface temperature jumps, heat-flux decay, and saves PNG figures.
%
% No synthetic COMSOL result is generated here. Missing files produce warnings
% and the script continues with the available data.

if nargin < 1
    userCfg = struct();
end

clc;

cfg.output_dir = 'COMSOL_EAHE_outputs';
cfg.delta_mm_list = [0, 0.5, 1, 2, 3, 5];
cfg.model_prefixes = {'explicit','resistance'};
cfg.model_names = {'explicit_gap','resistance_gap'};
cfg.rho_f = 1.20;                 % kg/m^3
cfg.cp_f = 1006.0;                % J/(kg K)
cfg.Vdot = 0.050;                 % m^3/s
cfg.mdot = cfg.rho_f * cfg.Vdot;  % kg/s
cfg.day_s = 24 * 3600;
cfg = apply_user_config(cfg, userCfg);

if ~exist(cfg.output_dir, 'dir')
    warning('Output directory does not exist: %s', cfg.output_dir);
    return
end

Tout = read_optional_table(fullfile(cfg.output_dir, 'COMSOL_Tout_delta_sweep.csv'));
Q = read_optional_table(fullfile(cfg.output_dir, 'COMSOL_Q_delta_sweep.csv'));
Interface = read_optional_table(fullfile(cfg.output_dir, 'COMSOL_interface_jump.csv'));
Annual = read_optional_table(fullfile(cfg.output_dir, 'COMSOL_annual_energy_summary.csv'));
Compare = read_optional_table(fullfile(cfg.output_dir, 'COMSOL_explicit_vs_resistance_gap.csv'));

if isempty(Q) && ~isempty(Tout)
    Q = compute_q_from_tout(Tout, cfg);
    writetable(Q, fullfile(cfg.output_dir, 'COMSOL_Q_delta_sweep.csv'));
end

if isempty(Annual) && ~isempty(Q)
    Annual = compute_annual_summary(Q, cfg);
    writetable(Annual, fullfile(cfg.output_dir, 'COMSOL_annual_energy_summary.csv'));
elseif ~isempty(Annual)
    Annual = recompute_dgap_if_needed(Annual);
    writetable(Annual, fullfile(cfg.output_dir, 'COMSOL_annual_energy_summary.csv'));
end

if isempty(Compare) && ~isempty(Tout)
    Compare = build_compare_from_tout(Tout, Interface, cfg);
    writetable(Compare, fullfile(cfg.output_dir, 'COMSOL_explicit_vs_resistance_gap.csv'));
end

Validation = compute_validation_metrics(Tout, Compare, cfg);
Performance = compute_performance_summary(Q, Annual, cfg);
Mechanism = compute_mechanism_summary(Interface, Tout, cfg);

writetable(Validation, fullfile(cfg.output_dir, 'COMSOL_validation_metrics.csv'));
writetable(Performance, fullfile(cfg.output_dir, 'COMSOL_performance_summary.csv'));
writetable(Mechanism, fullfile(cfg.output_dir, 'COMSOL_mechanism_chain_summary.csv'));

plot_tout_delta_sweep(Tout, cfg);
plot_tout_deviation(Tout, cfg);
plot_q_delta_sweep(Q, cfg);
plot_annual_energy(Annual, cfg);
plot_dgap(Annual, cfg);
plot_explicit_vs_resistance(Compare, cfg);
plot_interface_jump(Interface, cfg);
plot_qg_decay(Mechanism, cfg);

try_rc_comparisons(cfg);

fprintf('COMSOL EAHE postprocessing complete. Output directory: %s\n', cfg.output_dir);

end

function cfg = apply_user_config(cfg, userCfg)
    if isempty(userCfg)
        return
    end
    names = fieldnames(userCfg);
    for i = 1:numel(names)
        cfg.(names{i}) = userCfg.(names{i});
    end
    cfg.mdot = cfg.rho_f * cfg.Vdot;
end

function T = read_optional_table(fileName)
    if exist(fileName, 'file')
        T = readtable(fileName, 'VariableNamingRule', 'preserve');
    else
        warning('Missing file, skipped: %s', fileName);
        T = table();
    end
end

function Q = compute_q_from_tout(Tout, cfg)
    Q = table(Tout.t_day, 'VariableNames', {'t_day'});
    if ~ismember('Tin_C', Tout.Properties.VariableNames)
        warning('Tin_C column is missing. Cannot compute Q from Tout.');
        return
    end
    names = Tout.Properties.VariableNames;
    for i = 1:numel(names)
        name = names{i};
        if startsWith(name, 'Tout_') && endsWith(name, '_C')
            qName = strrep(name, 'Tout_', 'Q_');
            qName = regexprep(qName, '_C$', '_W');
            Q.(qName) = cfg.mdot * cfg.cp_f .* (Tout.Tin_C - Tout.(name));
        end
    end
end

function Annual = compute_annual_summary(Q, cfg)
    Annual = table();
    if isempty(Q) || ~ismember('t_day', Q.Properties.VariableNames)
        return
    end
    tSec = Q.t_day * cfg.day_s;
    names = Q.Properties.VariableNames;
    for i = 1:numel(names)
        name = names{i};
        if startsWith(name, 'Q_') && endsWith(name, '_W')
            [modelType, deltaMm] = parse_q_column(name);
            q = Q.(name);
            row = table(string(modelType), deltaMm, ...
                trapz(tSec, max(q, 0))/3.6e6, ...
                trapz(tSec, max(-q, 0))/3.6e6, ...
                trapz(tSec, abs(q))/3.6e6, NaN, ...
                'VariableNames', {'model_type','delta_mm','Ecool_kWh','Eheat_kWh','Eabs_kWh','Dgap_percent'});
            Annual = [Annual; row]; %#ok<AGROW>
        end
    end
    Annual = recompute_dgap_if_needed(Annual);
end

function Annual = recompute_dgap_if_needed(Annual)
    if isempty(Annual) || ~all(ismember({'model_type','delta_mm','Eabs_kWh'}, Annual.Properties.VariableNames))
        return
    end
    if ~ismember('Dgap_percent', Annual.Properties.VariableNames)
        Annual.Dgap_percent = NaN(height(Annual), 1);
    end
    types = unique(string(Annual.model_type));
    for iType = 1:numel(types)
        idxType = string(Annual.model_type) == types(iType);
        idx0 = idxType & Annual.delta_mm == 0;
        if ~any(idx0)
            continue
        end
        E0 = Annual.Eabs_kWh(find(idx0, 1));
        if ~isfinite(E0) || E0 == 0
            continue
        end
        Annual.Dgap_percent(idxType) = 100 * (1 - Annual.Eabs_kWh(idxType) ./ E0);
    end
end

function Compare = build_compare_from_tout(Tout, Interface, cfg)
    Compare = table();
    if isempty(Tout)
        return
    end
    for i = 1:numel(cfg.delta_mm_list)
        d = cfg.delta_mm_list(i);
        eCol = sprintf('Tout_explicit_delta_%s_C', delta_token(d));
        rCol = sprintf('Tout_resistance_delta_%s_C', delta_token(d));
        if ~all(ismember({eCol, rCol}, Tout.Properties.VariableNames))
            continue
        end
        n = height(Tout);
        [TpoE, TgE, DTintE] = interface_vectors(Interface, 'explicit_gap', d, Tout.t_day);
        [TpoR, TgR, DTintR] = interface_vectors(Interface, 'resistance_gap', d, Tout.t_day);
        rows = table(Tout.t_day, repmat(d, n, 1), ...
            Tout.(eCol), Tout.(rCol), Tout.(eCol)-Tout.(rCol), ...
            TpoE, TpoR, TgE, TgR, DTintE, DTintR, ...
            'VariableNames', {'t_day','delta_mm','Tout_explicit_C','Tout_resistance_C', ...
            'DeltaTout_C','Tpo_explicit_C','Tpo_resistance_C','Tg_explicit_C', ...
            'Tg_resistance_C','DeltaTint_explicit_C','DeltaTint_resistance_C'});
        Compare = [Compare; rows]; %#ok<AGROW>
    end
end

function [Tpo, Tg, DTint] = interface_vectors(Interface, modelType, deltaMm, tDay)
    n = numel(tDay);
    Tpo = nan(n, 1);
    Tg = nan(n, 1);
    DTint = nan(n, 1);
    if isempty(Interface) || ~all(ismember({'model_type','delta_mm','t_day'}, Interface.Properties.VariableNames))
        return
    end
    idx = string(Interface.model_type) == string(modelType) & abs(Interface.delta_mm - deltaMm) < 1e-9;
    if ~any(idx)
        return
    end
    rows = Interface(idx, :);
    if ismember('Tpo_mid_C', rows.Properties.VariableNames)
        Tpo = interp1(rows.t_day, rows.Tpo_mid_C, tDay, 'linear', NaN);
    end
    if ismember('Tg_mid_C', rows.Properties.VariableNames)
        Tg = interp1(rows.t_day, rows.Tg_mid_C, tDay, 'linear', NaN);
    end
    if ismember('DeltaTint_mid_C', rows.Properties.VariableNames)
        DTint = interp1(rows.t_day, rows.DeltaTint_mid_C, tDay, 'linear', NaN);
    else
        DTint = Tpo - Tg;
    end
end

function Validation = compute_validation_metrics(Tout, Compare, cfg)
    Validation = table();
    if ~isempty(Compare)
        deltas = unique(Compare.delta_mm);
        for i = 1:numel(deltas)
            d = deltas(i);
            rows = Compare(abs(Compare.delta_mm - d) < 1e-9, :);
            if isempty(rows)
                continue
            end
            e = rows.Tout_explicit_C;
            r = rows.Tout_resistance_C;
            diff = e - r;
            row = table(d, rmse(diff), mean(abs(diff), 'omitnan'), max(abs(diff), [], 'omitnan'), ...
                'VariableNames', {'delta_mm','RMSE_Tout_C','MAE_Tout_C','MaxAbs_Tout_C'});
            Validation = [Validation; row]; %#ok<AGROW>
        end
    elseif ~isempty(Tout)
        for i = 1:numel(cfg.delta_mm_list)
            d = cfg.delta_mm_list(i);
            eCol = sprintf('Tout_explicit_delta_%s_C', delta_token(d));
            rCol = sprintf('Tout_resistance_delta_%s_C', delta_token(d));
            if all(ismember({eCol, rCol}, Tout.Properties.VariableNames))
                diff = Tout.(eCol) - Tout.(rCol);
                row = table(d, rmse(diff), mean(abs(diff), 'omitnan'), max(abs(diff), [], 'omitnan'), ...
                    'VariableNames', {'delta_mm','RMSE_Tout_C','MAE_Tout_C','MaxAbs_Tout_C'});
                Validation = [Validation; row]; %#ok<AGROW>
            end
        end
    end
end

function Performance = compute_performance_summary(Q, Annual, cfg)
    if ~isempty(Annual)
        Performance = Annual;
        return
    end
    Performance = compute_annual_summary(Q, cfg);
end

function Mechanism = compute_mechanism_summary(Interface, Tout, cfg)
    Mechanism = table();
    if isempty(Interface) || ~all(ismember({'model_type','delta_mm','t_day'}, Interface.Properties.VariableNames))
        return
    end
    types = unique(string(Interface.model_type));
    for iType = 1:numel(types)
        type = types(iType);
        base = Interface(string(Interface.model_type) == type & Interface.delta_mm == 0, :);
        baseInt = NaN;
        if ~isempty(base) && ismember('qg_mid_W_per_m', base.Properties.VariableNames)
            baseInt = trapz(base.t_day * cfg.day_s, abs(base.qg_mid_W_per_m));
        end
        deltas = unique(Interface.delta_mm(string(Interface.model_type) == type));
        for i = 1:numel(deltas)
            d = deltas(i);
            rows = Interface(string(Interface.model_type) == type & abs(Interface.delta_mm - d) < 1e-9, :);
            if isempty(rows)
                continue
            end
            meanDT = col_mean_abs(rows, 'DeltaTint_mid_C');
            meanQG = col_mean_abs(rows, 'qg_mid_W_per_m');
            Dq = NaN;
            if isfinite(baseInt) && baseInt ~= 0 && ismember('qg_mid_W_per_m', rows.Properties.VariableNames)
                thisInt = trapz(rows.t_day * cfg.day_s, abs(rows.qg_mid_W_per_m));
                Dq = 100 * (1 - thisInt / baseInt);
            end
            meanToutDev = tout_deviation_mean(Tout, char(type), d);
            row = table(type, d, meanDT, meanQG, Dq, meanToutDev, ...
                'VariableNames', {'model_type','delta_mm','MeanAbs_DeltaTint_C', ...
                'MeanAbs_qg_W_per_m','Dq_percent','Mean_Tout_deviation_vs_0mm_C'});
            Mechanism = [Mechanism; row]; %#ok<AGROW>
        end
    end
end

function value = col_mean_abs(T, name)
    if ismember(name, T.Properties.VariableNames)
        value = mean(abs(T.(name)), 'omitnan');
    else
        value = NaN;
    end
end

function value = tout_deviation_mean(Tout, modelType, deltaMm)
    value = NaN;
    if isempty(Tout)
        return
    end
    prefix = model_prefix_from_type(modelType);
    col = sprintf('Tout_%s_delta_%s_C', prefix, delta_token(deltaMm));
    base = sprintf('Tout_%s_delta_0mm_C', prefix);
    if all(ismember({col, base}, Tout.Properties.VariableNames))
        value = mean(Tout.(col) - Tout.(base), 'omitnan');
    end
end

function plot_tout_delta_sweep(Tout, cfg)
    if isempty(Tout)
        return
    end
    fig = new_fig();
    if ismember('Tin_C', Tout.Properties.VariableNames)
        plot(Tout.t_day, Tout.Tin_C, 'k-', 'LineWidth', 1.5, 'DisplayName', 'Tin');
        hold on;
    end
    plot_columns_by_prefix(Tout, 'Tout_', '_C', 'LineWidth', 1.0);
    xlabel('Time / day');
    ylabel('Temperature / degC');
    title('COMSOL outlet temperature delta sweep');
    legend('Location', 'bestoutside');
    grid on;
    save_fig(fig, cfg, 'Fig_COMSOL_01_Tout_delta_sweep.png');
end

function plot_tout_deviation(Tout, cfg)
    if isempty(Tout)
        return
    end
    fig = new_fig();
    hold on;
    for iType = 1:numel(cfg.model_prefixes)
        prefix = cfg.model_prefixes{iType};
        base = sprintf('Tout_%s_delta_0mm_C', prefix);
        if ~ismember(base, Tout.Properties.VariableNames)
            continue
        end
        for i = 1:numel(cfg.delta_mm_list)
            d = cfg.delta_mm_list(i);
            col = sprintf('Tout_%s_delta_%s_C', prefix, delta_token(d));
            if ismember(col, Tout.Properties.VariableNames)
                plot(Tout.t_day, Tout.(col)-Tout.(base), 'LineWidth', 1.0, ...
                    'DisplayName', sprintf('%s %.3g mm', prefix, d));
            end
        end
    end
    xlabel('Time / day');
    ylabel('Outlet temperature deviation vs 0 mm / degC');
    title('COMSOL outlet temperature deviation');
    legend('Location', 'bestoutside');
    grid on;
    save_fig(fig, cfg, 'Fig_COMSOL_02_Tout_deviation.png');
end

function plot_q_delta_sweep(Q, cfg)
    if isempty(Q)
        return
    end
    fig = new_fig();
    plot_columns_by_prefix(Q, 'Q_', '_W', 'LineWidth', 1.0);
    xlabel('Time / day');
    ylabel('Heat transfer rate / W');
    title('COMSOL instantaneous heat transfer rate');
    legend('Location', 'bestoutside');
    grid on;
    save_fig(fig, cfg, 'Fig_COMSOL_03_Q_delta_sweep.png');
end

function plot_annual_energy(Annual, cfg)
    if isempty(Annual)
        return
    end
    fig = new_fig();
    tiledlayout(1, numel(unique(string(Annual.model_type))), 'TileSpacing', 'compact');
    types = unique(string(Annual.model_type));
    for i = 1:numel(types)
        nexttile;
        rows = Annual(string(Annual.model_type) == types(i), :);
        bar(rows.delta_mm, [rows.Ecool_kWh, rows.Eheat_kWh, rows.Eabs_kWh]);
        xlabel('\delta / mm');
        ylabel('Energy / kWh');
        title(char(types(i)));
        legend({'Ecool','Eheat','Eabs'}, 'Location', 'best');
        grid on;
    end
    save_fig(fig, cfg, 'Fig_COMSOL_04_annual_energy.png');
end

function plot_dgap(Annual, cfg)
    if isempty(Annual) || ~ismember('Dgap_percent', Annual.Properties.VariableNames)
        return
    end
    fig = new_fig();
    hold on;
    types = unique(string(Annual.model_type));
    for i = 1:numel(types)
        rows = Annual(string(Annual.model_type) == types(i), :);
        plot(rows.delta_mm, rows.Dgap_percent, 'o-', 'LineWidth', 1.2, 'DisplayName', char(types(i)));
    end
    xlabel('\delta / mm');
    ylabel('Dgap / %');
    title('Air-gap performance degradation factor');
    legend('Location', 'best');
    grid on;
    save_fig(fig, cfg, 'Fig_COMSOL_05_Dgap.png');
end

function plot_explicit_vs_resistance(Compare, cfg)
    if isempty(Compare)
        return
    end
    fig = new_fig();
    hold on;
    deltas = unique(Compare.delta_mm);
    for i = 1:numel(deltas)
        d = deltas(i);
        rows = Compare(abs(Compare.delta_mm - d) < 1e-9, :);
        plot(rows.t_day, rows.Tout_explicit_C, '-', 'LineWidth', 1.0, ...
            'DisplayName', sprintf('explicit %.3g mm', d));
        plot(rows.t_day, rows.Tout_resistance_C, '--', 'LineWidth', 1.0, ...
            'DisplayName', sprintf('resistance %.3g mm', d));
    end
    xlabel('Time / day');
    ylabel('Outlet temperature / degC');
    title('Explicit gap vs equivalent resistance: Tout');
    legend('Location', 'bestoutside');
    grid on;
    save_fig(fig, cfg, 'Fig_COMSOL_06_explicit_vs_resistance_Tout.png');
end

function plot_interface_jump(Interface, cfg)
    if isempty(Interface) || ~ismember('DeltaTint_mid_C', Interface.Properties.VariableNames)
        return
    end
    fig = new_fig();
    hold on;
    for i = 1:height(Interface)
        if ~isfinite(Interface.DeltaTint_mid_C(i))
            continue
        end
    end
    keys = unique(string(Interface.model_type) + "_" + string(Interface.delta_mm));
    for k = 1:numel(keys)
        parts = split(keys(k), "_");
        d = str2double(parts(end));
        type = join(parts(1:end-1), "_");
        rows = Interface(string(Interface.model_type) == type & abs(Interface.delta_mm - d) < 1e-9, :);
        plot(rows.t_day, rows.DeltaTint_mid_C, 'LineWidth', 1.0, ...
            'DisplayName', sprintf('%s %.3g mm', char(type), d));
    end
    xlabel('Time / day');
    ylabel('Interface temperature jump / degC');
    title('Mid-pipe interface temperature jump');
    legend('Location', 'bestoutside');
    grid on;
    save_fig(fig, cfg, 'Fig_COMSOL_07_interface_jump.png');
end

function plot_qg_decay(Mechanism, cfg)
    if isempty(Mechanism) || ~ismember('Dq_percent', Mechanism.Properties.VariableNames)
        return
    end
    fig = new_fig();
    hold on;
    types = unique(string(Mechanism.model_type));
    for i = 1:numel(types)
        rows = Mechanism(string(Mechanism.model_type) == types(i), :);
        plot(rows.delta_mm, rows.Dq_percent, 'o-', 'LineWidth', 1.2, 'DisplayName', char(types(i)));
    end
    xlabel('\delta / mm');
    ylabel('Dq / %');
    title('Interface heat-flux decay');
    legend('Location', 'best');
    grid on;
    save_fig(fig, cfg, 'Fig_COMSOL_08_qg_decay.png');
end

function plot_columns_by_prefix(T, prefix, suffix, varargin)
    names = T.Properties.VariableNames;
    hold on;
    for i = 1:numel(names)
        name = names{i};
        if startsWith(name, prefix) && endsWith(name, suffix)
            plot(T.t_day, T.(name), varargin{:}, 'DisplayName', strrep(name, '_', '\_'));
        end
    end
end

function fig = new_fig()
    fig = figure('Color', 'w', 'Visible', 'off');
end

function save_fig(fig, cfg, fileName)
    fullName = fullfile(cfg.output_dir, fileName);
    try
        exportgraphics(fig, fullName, 'Resolution', 300);
    catch
        saveas(fig, fullName);
    end
    close(fig);
end

function try_rc_comparisons(cfg)
    pairs = {
        'COMSOL_Tout_delta_sweep.csv', 'EAHE_RC_Tout_delta_sweep.csv';
        'COMSOL_Q_delta_sweep.csv', 'EAHE_RC_Q_delta_sweep.csv';
        'COMSOL_interface_jump.csv', 'EAHE_RC_interface_jump.csv';
        'COMSOL_annual_energy_summary.csv', 'EAHE_RC_annual_energy_summary.csv'};

    allRows = table();
    for i = 1:size(pairs, 1)
        cFile = fullfile(cfg.output_dir, pairs{i, 1});
        rFile = fullfile(cfg.output_dir, pairs{i, 2});
        rows = compare_comsol_with_rc(cFile, rFile);
        if ~isempty(rows)
            rows.source_pair = repmat(string(pairs{i, 1}), height(rows), 1);
            allRows = [allRows; rows]; %#ok<AGROW>
        end
    end
    if ~isempty(allRows)
        writetable(allRows, fullfile(cfg.output_dir, 'COMSOL_vs_RC_metrics.csv'));
    end
end

function metrics = compare_comsol_with_rc(comsolFile, rcFile)
    metrics = table();
    if ~exist(comsolFile, 'file')
        warning('COMSOL file does not exist, skipped RC comparison: %s', comsolFile);
        return
    end
    if ~exist(rcFile, 'file')
        warning('RC file does not exist, skipped RC comparison: %s', rcFile);
        return
    end

    C = readtable(comsolFile, 'VariableNamingRule', 'preserve');
    R = readtable(rcFile, 'VariableNamingRule', 'preserve');
    cNames = C.Properties.VariableNames;
    rNames = R.Properties.VariableNames;

    common = intersect(cNames, rNames, 'stable');
    common = setdiff(common, {'t_day','Tin_C','model_type','delta_mm'}, 'stable');
    for i = 1:numel(common)
        col = common{i};
        if ~isnumeric(C.(col)) || ~isnumeric(R.(col))
            continue
        end
        n = min(height(C), height(R));
        diff = C.(col)(1:n) - R.(col)(1:n);
        row = table(string(col), rmse(diff), mean(abs(diff), 'omitnan'), ...
            max(abs(diff), [], 'omitnan'), NaN, ...
            'VariableNames', {'quantity','RMSE_Tout','MAE_Tout','MaxAbs_Tout','RelError_Eabs_percent'});
        metrics = [metrics; row]; %#ok<AGROW>
    end

    if all(ismember({'model_type','delta_mm','Eabs_kWh'}, cNames)) && ...
            all(ismember({'model_type','delta_mm','Eabs_kWh'}, rNames))
        for i = 1:height(C)
            idx = string(R.model_type) == string(C.model_type(i)) & abs(R.delta_mm - C.delta_mm(i)) < 1e-9;
            if any(idx)
                rcE = R.Eabs_kWh(find(idx, 1));
                rel = 100 * (C.Eabs_kWh(i) - rcE) / rcE;
                row = table("Eabs_kWh", NaN, NaN, NaN, rel, ...
                    'VariableNames', {'quantity','RMSE_Tout','MAE_Tout','MaxAbs_Tout','RelError_Eabs_percent'});
                metrics = [metrics; row]; %#ok<AGROW>
            end
        end
    end
end

function y = rmse(x)
    y = sqrt(mean(x.^2, 'omitnan'));
end

function [modelType, deltaMm] = parse_q_column(name)
    token = regexp(name, '^Q_(explicit|resistance)_delta_(.+)_W$', 'tokens', 'once');
    if isempty(token)
        modelType = "";
        deltaMm = NaN;
        return
    end
    if strcmp(token{1}, 'explicit')
        modelType = "explicit_gap";
    else
        modelType = "resistance_gap";
    end
    deltaMm = str2double(strrep(erase(token{2}, 'mm'), 'p', '.'));
end

function prefix = model_prefix_from_type(modelType)
    if strcmpi(modelType, 'explicit_gap')
        prefix = 'explicit';
    else
        prefix = 'resistance';
    end
end

function tok = delta_token(deltaMm)
    if abs(deltaMm - round(deltaMm)) < 1e-12
        tok = sprintf('%gmm', deltaMm);
    else
        tok = strrep(sprintf('%gmm', deltaMm), '.', 'p');
    end
end
