"""Fallback exporter for EAHE results when MATLAB cannot start.

This script reads existing .mat/.csv result files and regenerates PNG figures
in the existing figures/* folders. It also exports summary tables and a compact
key-finding text file. MATLAB .fig files are not generated by this fallback.
"""

import math
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.io as sio
from scipy.interpolate import griddata


ROOT = Path(__file__).resolve().parent
FIGROOT = ROOT / "figures"
CURRENT_REVISION = "soil_phase_offset_v2"


def loadmat(name: str) -> dict:
    return sio.loadmat(ROOT / name, squeeze_me=True, struct_as_record=False)


def arr(x):
    return np.asarray(x).squeeze()


def ensure_clean(folder: Path):
    folder.mkdir(parents=True, exist_ok=True)
    for path in folder.glob("*.png"):
        path.unlink()


def savefig(folder: str, filename: str):
    path = FIGROOT / folder
    path.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(path / filename, dpi=300)
    plt.close()


def result_list(obj):
    if isinstance(obj, np.ndarray):
        return [obj.flat[i] for i in range(obj.size)]
    return [obj]


def result_revision(result) -> str:
    try:
        return str(result.param.model_revision)
    except Exception:
        return "<unknown>"


def is_current_result(result) -> bool:
    return result_revision(result) == CURRENT_REVISION


def require_current(result, name: str) -> bool:
    rev = result_revision(result)
    if rev != CURRENT_REVISION:
        print(f"Skipping {name}: result revision is {rev}, expected {CURRENT_REVISION}.")
        return False
    return True


def plot_baseline():
    p = ROOT / "baseline_result.mat"
    if not p.exists():
        return
    ensure_clean(FIGROOT / "baseline")
    r = loadmat(p.name)["result"]
    if not require_current(r, p.name):
        return
    t = arr(r.time) / 3600
    idx = np.arange(1, len(t))

    plt.figure(figsize=(12, 6))
    plt.plot(t[idx], arr(r.Tin)[idx], "k--", lw=1.2, label="Inlet air")
    plt.plot(t[idx], arr(r.Tout)[idx], "b-", lw=1.5, label="Outlet air")
    plt.xlabel("Time / h")
    plt.ylabel("Temperature / degC")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("baseline", "baseline_01_EAHE_inlet_and_outlet_temperature.png")

    plt.figure(figsize=(12, 6))
    plt.plot(t[idx], arr(r.Q)[idx], "r-", lw=1.5)
    plt.xlabel("Time / h")
    plt.ylabel("Heat transfer rate / W")
    plt.grid(True, alpha=0.35)
    savefig("baseline", "baseline_02_EAHE_heat_transfer_rate.png")

    plt.figure(figsize=(12, 6))
    und = arr(r.Tundist_pipe)
    plt.plot(t, arr(r.Tsoil_near_mid_mean) - und, "m-", lw=1.5, label="Mean")
    plt.plot(t, arr(r.Tsoil_near_mid_top) - und, "b--", lw=1.1, label="Top sector")
    plt.plot(t, arr(r.Tsoil_near_mid_bottom) - und, "r--", lw=1.1, label="Bottom sector")
    plt.xlabel("Time / h")
    plt.ylabel("Near-pipe soil temperature rise / K")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("baseline", "baseline_03_Near-pipe_soil_thermal_accumulation.png")

    d = r.degradation
    plt.figure(figsize=(9, 5))
    ax1 = plt.gca()
    ax1.plot(arr(d.day), arr(d.eta_Q_day), "ro-", lw=1.3)
    ax1.set_xlabel("Operation day")
    ax1.set_ylabel("Q day mean / day-1 value", color="r")
    ax1.tick_params(axis="y", labelcolor="r")
    ax1.grid(True, alpha=0.35)
    ax2 = ax1.twinx()
    ax2.plot(arr(d.day), arr(d.near_soil_rise_day_mean), "bs-", lw=1.3)
    ax2.set_ylabel("Mean near-pipe soil rise / K", color="b")
    ax2.tick_params(axis="y", labelcolor="b")
    savefig("baseline", "baseline_04_Daily_degradation_metrics.png")


def plot_degradation():
    p = ROOT / "degradation_validation_result.mat"
    if not p.exists():
        return
    ensure_clean(FIGROOT / "degradation")
    data = loadmat(p.name)
    no_gap = data["case_no_gap"]
    gap = data["case_gap"]
    if not require_current(no_gap, p.name):
        return

    plt.figure(figsize=(9, 5))
    plt.plot(arr(no_gap.degradation.day), arr(no_gap.degradation.Q_day_mean), "bo-", lw=1.3, label="No gap")
    plt.plot(arr(gap.degradation.day), arr(gap.degradation.Q_day_mean), "rs-", lw=1.3, label="Fixed gap")
    plt.xlabel("Operation day")
    plt.ylabel("Daily mean heat transfer rate / W")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("degradation", "degradation_01_Thermal_degradation_-_daily_mean_heat_transfer.png")

    plt.figure(figsize=(9, 5))
    plt.plot(arr(no_gap.degradation.day), arr(no_gap.degradation.eta_Q_day), "bo-", lw=1.3, label="No gap")
    plt.plot(arr(gap.degradation.day), arr(gap.degradation.eta_Q_day), "rs-", lw=1.3, label="Fixed gap")
    plt.xlabel("Operation day")
    plt.ylabel("Q day mean / day-1 value")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("degradation", "degradation_02_Thermal_degradation_ratio.png")

    plt.figure(figsize=(9, 5))
    plt.plot(arr(no_gap.degradation.day), arr(no_gap.degradation.near_soil_rise_day_mean), "bo-", lw=1.3, label="No gap")
    plt.plot(arr(gap.degradation.day), arr(gap.degradation.near_soil_rise_day_mean), "rs-", lw=1.3, label="Fixed gap")
    plt.xlabel("Operation day")
    plt.ylabel("Daily mean near-pipe soil temperature rise / K")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("degradation", "degradation_03_Near-pipe_soil_heat_accumulation.png")


def plot_gap_thickness():
    p = ROOT / "gap_sensitivity_result.mat"
    if not p.exists():
        return
    ensure_clean(FIGROOT / "gap_thickness")
    data = loadmat(p.name)
    cases = result_list(data["results"])
    if cases and not require_current(cases[0], p.name):
        return
    gaps = arr(data["gap_list"]) * 1e3
    labels = [fr"$\delta_{{gap}}={g:.1f}$ mm" for g in gaps]

    plt.figure(figsize=(12, 6))
    for c, lab in zip(cases, labels):
        t = arr(c.time) / 3600
        idx = np.arange(1, len(t))
        plt.plot(t[idx], arr(c.Tout)[idx], lw=1.2, label=lab)
    plt.xlabel("Time / h")
    plt.ylabel("Outlet air temperature / degC")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("gap_thickness", "gap_thickness_01_Gap_sensitivity_-_outlet_temperature.png")

    plt.figure(figsize=(12, 6))
    for c, lab in zip(cases, labels):
        t = arr(c.time) / 3600
        idx = np.arange(1, len(t))
        plt.plot(t[idx], arr(c.Q)[idx], lw=1.2, label=lab)
    plt.xlabel("Time / h")
    plt.ylabel("Heat transfer rate / W")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("gap_thickness", "gap_thickness_02_Gap_sensitivity_-_heat_transfer_rate.png")

    plt.figure(figsize=(9, 5))
    for c, lab in zip(cases, labels):
        plt.plot(arr(c.degradation.day), arr(c.degradation.Q_day_mean), "o-", lw=1.2, label=lab)
    plt.xlabel("Operation day")
    plt.ylabel("Daily mean heat transfer rate / W")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("gap_thickness", "gap_thickness_03_Gap_sensitivity_-_daily_mean_heat_transfer.png")


def plot_gap_conductivity():
    p = ROOT / "gap_conductivity_sensitivity_result.mat"
    if not p.exists():
        return
    ensure_clean(FIGROOT / "gap_conductivity")
    data = loadmat(p.name)
    cases = result_list(data["results"])
    if cases and not require_current(cases[0], p.name):
        return
    kvals = arr(data["k_gap_list"])
    labels = [fr"$k_{{gap}}={k:.3f}$ W/(m K)" for k in kvals]

    plt.figure(figsize=(12, 6))
    for c, lab in zip(cases, labels):
        t = arr(c.time) / 3600
        idx = np.arange(1, len(t))
        plt.plot(t[idx], arr(c.Tout)[idx], lw=1.2, label=lab)
    plt.xlabel("Time / h")
    plt.ylabel("Outlet air temperature / degC")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("gap_conductivity", "gap_conductivity_01_Gap_conductivity_sensitivity_-_outlet_temperature.png")

    plt.figure(figsize=(9, 5))
    for c, lab in zip(cases, labels):
        plt.plot(arr(c.degradation.day), arr(c.degradation.Q_day_mean), "o-", lw=1.2, label=lab)
    plt.xlabel("Operation day")
    plt.ylabel("Daily mean heat transfer rate / W")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("gap_conductivity", "gap_conductivity_02_Gap_conductivity_sensitivity_-_daily_mean_heat_transfer.png")


def plot_operation():
    p = ROOT / "operation_sensitivity_result.mat"
    if not p.exists():
        return
    ensure_clean(FIGROOT / "operation")
    data = loadmat(p.name)
    m_cases = result_list(data["m_results"])
    mvals = arr(data["m_dot_list"])
    L_cases = result_list(data["L_results"])
    if m_cases and not require_current(m_cases[0], p.name):
        return
    Lvals = arr(data["L_list"])

    plt.figure(figsize=(12, 6))
    for c, m in zip(m_cases, mvals):
        t = arr(c.time) / 3600
        idx = np.arange(1, len(t))
        plt.plot(t[idx], arr(c.Tout)[idx], lw=1.2, label=fr"$\dot m={m:.2f}$ kg/s")
    plt.xlabel("Time / h")
    plt.ylabel("Outlet air temperature / degC")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("operation", "operation_01_Mass_flow_sensitivity_-_outlet_temperature.png")

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    for c, m in zip(m_cases, mvals):
        axes[0].plot(arr(c.degradation.day), arr(c.degradation.Q_day_mean), "o-", lw=1.2, label=fr"$\dot m={m:.2f}$ kg/s")
        axes[1].plot(arr(c.degradation.day), arr(c.degradation.dT_day_mean), "o-", lw=1.2)
    axes[0].set_xlabel("Operation day")
    axes[0].set_ylabel("Daily mean heat transfer / W")
    axes[1].set_xlabel("Operation day")
    axes[1].set_ylabel("Daily mean Tin - Tout / K")
    for ax in axes:
        ax.grid(True, alpha=0.35)
    axes[0].legend()
    savefig("operation", "operation_02_Mass_flow_sensitivity_-_daily_heat_and_cooling_drop.png")

    plt.figure(figsize=(12, 6))
    for c, L in zip(L_cases, Lvals):
        t = arr(c.time) / 3600
        idx = np.arange(1, len(t))
        plt.plot(t[idx], arr(c.Tout)[idx], lw=1.2, label=fr"$L={L:.0f}$ m")
    plt.xlabel("Time / h")
    plt.ylabel("Outlet air temperature / degC")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("operation", "operation_03_Pipe_length_sensitivity_-_outlet_temperature.png")


def plot_soil_layer2():
    p = ROOT / "soil_layer2_sensitivity_result.mat"
    if not p.exists():
        return
    ensure_clean(FIGROOT / "soil_layer2")
    data = loadmat(p.name)
    cases = result_list(data["results"])
    if cases and not require_current(cases[0], p.name):
        return
    kvals = arr(data["k2_list"])
    labels = [fr"$k_2={k:.2f}$ W/(m K)" for k in kvals]

    plt.figure(figsize=(12, 6))
    for c, lab in zip(cases, labels):
        t = arr(c.time) / 3600
        idx = np.arange(1, len(t))
        plt.plot(t[idx], arr(c.Tout)[idx], lw=1.2, label=lab)
    plt.xlabel("Time / h")
    plt.ylabel("Outlet air temperature / degC")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("soil_layer2", "soil_layer2_01_Layer-2_soil_conductivity_sensitivity_-_outlet_temperature.png")

    plt.figure(figsize=(9, 5))
    for c, lab in zip(cases, labels):
        plt.plot(arr(c.degradation.day), arr(c.degradation.Q_day_mean), "o-", lw=1.2, label=lab)
    plt.xlabel("Operation day")
    plt.ylabel("Daily mean heat transfer rate / W")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("soil_layer2", "soil_layer2_02_Layer-2_soil_conductivity_sensitivity_-_daily_heat_transfer.png")


def idx_ts(i, m, r, param):
    nseg = int(param.nNode_seg)
    nr = int(param.Nr)
    return (i - 1) * nseg + 2 + (m - 1) * nr + r - 1


def plot_temperature_contours():
    p = ROOT / "temperature_field_fine_result.mat"
    if not p.exists():
        return
    ensure_clean(FIGROOT / "temperature_field_fine")
    result = loadmat(p.name)["result"]
    if not require_current(result, p.name):
        return
    param = result.param
    geom = result.geom
    times = np.atleast_1d(arr(result.snapshots.time))
    Xmat = np.asarray(result.snapshots.X)
    if Xmat.ndim == 1:
        Xmat = Xmat[:, None]

    nx = int(param.Nx_pipe)
    ntheta = int(param.Ntheta)
    nr = int(param.Nr)
    mid = round(nx / 2)
    theta = arr(geom.theta)
    rcenters = arr(geom.r_centers)
    ro = float(param.r_o)
    rmax = float(param.r_soil_max)
    zpipe = float(param.z_pipe)

    for k, time_s in enumerate(times):
        X = Xmat[:, k]
        xs, zs, ts = [], [], []
        for mi in range(1, ntheta + 1):
            th = theta[mi - 1]
            for ri in range(1, nr + 1):
                rr = rcenters[ri - 1]
                xs.append(rr * math.cos(th))
                zs.append(zpipe + rr * math.sin(th))
                ts.append(X[idx_ts(mid, mi, ri, param)])
        xs, zs, ts = map(np.asarray, (xs, zs, ts))

        xq = np.linspace(-rmax, rmax, 260)
        zq = np.linspace(zpipe - rmax, zpipe + rmax, 260)
        Xq, Zq = np.meshgrid(xq, zq)
        Tq = griddata((xs, zs), ts, (Xq, Zq), method="cubic")
        if np.isnan(Tq).any():
            Tlin = griddata((xs, zs), ts, (Xq, Zq), method="linear")
            Tq = np.where(np.isnan(Tq), Tlin, Tq)
        Rq = np.sqrt(Xq**2 + (Zq - zpipe) ** 2)
        Tq[(Rq < ro) | (Rq > rmax) | (Zq < 0)] = np.nan

        plt.figure(figsize=(8, 9))
        cf = plt.contourf(Xq, Zq, Tq, 32, cmap="viridis")
        plt.colorbar(cf, label="Temperature / degC")
        th = np.linspace(0, 2 * np.pi, 300)
        plt.plot(ro * np.cos(th), zpipe + ro * np.sin(th), "k-", lw=2)
        for zb, lab in zip(arr(param.z_layer_bot)[:2], ["Layer 1/2", "Layer 2/3"]):
            plt.axhline(zb, color="k", ls="--", lw=1, alpha=0.65)
            plt.text(-rmax * 0.98, zb, lab, va="bottom", ha="left", fontsize=9)
        plt.gca().invert_yaxis()
        plt.axis("equal")
        plt.xlabel("Horizontal distance from pipe center / m")
        plt.ylabel("Depth / m")
        plt.title(f"Near-pipe soil temperature, t = {time_s/3600:.1f} h, segment = {mid}")
        savefig("temperature_field_fine", f"contour_fine_{k+1:02d}_Temperature_contour_{time_s/3600:.1f}_h.png")


def plot_variable_gap_sensitivity():
    p = ROOT / "variable_gap_sensitivity_result.mat"
    if not p.exists():
        return
    ensure_clean(FIGROOT / "variable_gap_sensitivity")
    data = loadmat(p.name)
    cases = result_list(data["results"])
    if cases and not require_current(cases[0], p.name):
        return
    avals = arr(data["a_list"])
    labels = [fr"$a_{{gap,T}}={a:.3f}$ 1/K" for a in avals]

    plt.figure(figsize=(12, 6))
    for c, lab in zip(cases, labels):
        t = arr(c.time) / 3600
        idx = np.arange(1, len(t))
        plt.plot(t[idx], arr(c.Tout)[idx], lw=1.2, label=lab)
    plt.xlabel("Time / h")
    plt.ylabel("Outlet air temperature / degC")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("variable_gap_sensitivity", "variable_gap_sensitivity_01_outlet_temperature.png")

    plt.figure(figsize=(9, 5))
    for c, lab in zip(cases, labels):
        plt.plot(arr(c.degradation.day), arr(c.degradation.Q_day_mean), "o-", lw=1.2, label=lab)
    plt.xlabel("Operation day")
    plt.ylabel("Daily mean heat transfer rate / W")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("variable_gap_sensitivity", "variable_gap_sensitivity_02_daily_mean_heat_transfer.png")

    plt.figure(figsize=(12, 6))
    for c, lab in zip(cases, labels):
        plt.plot(arr(c.time) / 3600, arr(c.Rgap_factor_mid_mean), lw=1.2, label=lab)
    plt.xlabel("Time / h")
    plt.ylabel("Mean Rgap factor at middle segment")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("variable_gap_sensitivity", "variable_gap_sensitivity_03_gap_resistance_factor.png")


def plot_variable_gap_extension():
    p = ROOT / "variable_gap_extension_result.mat"
    if not p.exists():
        return
    ensure_clean(FIGROOT / "variable_gap")
    data = loadmat(p.name)
    fixed = data["fixed_case"]
    variable = data["variable_case"]
    if not require_current(fixed, p.name):
        return

    idx_f = np.arange(1, len(arr(fixed.time)))
    idx_v = np.arange(1, len(arr(variable.time)))

    plt.figure(figsize=(12, 6))
    plt.plot(arr(fixed.time)[idx_f] / 3600, arr(fixed.Tout)[idx_f], "b-", lw=1.4, label="Fixed Rgap")
    plt.plot(arr(variable.time)[idx_v] / 3600, arr(variable.Tout)[idx_v], "r--", lw=1.4, label="Variable Rgap")
    plt.xlabel("Time / h")
    plt.ylabel("Outlet air temperature / degC")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("variable_gap", "variable_gap_01_outlet_temperature.png")

    plt.figure(figsize=(12, 6))
    plt.plot(arr(fixed.time)[idx_f] / 3600, arr(fixed.Q)[idx_f], "b-", lw=1.4, label="Fixed Rgap")
    plt.plot(arr(variable.time)[idx_v] / 3600, arr(variable.Q)[idx_v], "r--", lw=1.4, label="Variable Rgap")
    plt.xlabel("Time / h")
    plt.ylabel("Heat transfer rate / W")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("variable_gap", "variable_gap_02_heat_transfer_rate.png")

    plt.figure(figsize=(12, 6))
    plt.plot(arr(variable.time) / 3600, arr(variable.Rgap_factor_mid_mean), "m-", lw=1.4)
    plt.xlabel("Time / h")
    plt.ylabel("Mean Rgap factor at middle segment")
    plt.grid(True, alpha=0.35)
    savefig("variable_gap", "variable_gap_03_gap_resistance_factor.png")

    plt.figure(figsize=(9, 5))
    plt.plot(arr(fixed.degradation.day), arr(fixed.degradation.Q_day_mean), "bo-", lw=1.3, label="Fixed Rgap")
    plt.plot(arr(variable.degradation.day), arr(variable.degradation.Q_day_mean), "rs-", lw=1.3, label="Variable Rgap")
    plt.xlabel("Operation day")
    plt.ylabel("Daily mean heat transfer rate / W")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("variable_gap", "variable_gap_04_daily_degradation.png")


def plot_numerical_validation():
    p = ROOT / "numerical_validation_result.mat"
    if not p.exists():
        return
    ensure_clean(FIGROOT / "numerical_validation")
    data = loadmat(p.name)
    dt_cases = result_list(data["dt_results"])
    if dt_cases and not require_current(dt_cases[0], p.name):
        return

    dt_list = arr(data["dt_list"]) if "dt_list" in data else np.array([60, 300, 600])
    dt_summary = pd.read_csv(ROOT / "validation_dt_summary.csv") if (ROOT / "validation_dt_summary.csv").exists() else None
    nx_summary = pd.read_csv(ROOT / "validation_Nx_summary.csv") if (ROOT / "validation_Nx_summary.csv").exists() else None
    nt_summary = pd.read_csv(ROOT / "validation_Ntheta_summary.csv") if (ROOT / "validation_Ntheta_summary.csv").exists() else None
    nr_summary = pd.read_csv(ROOT / "validation_Nr_summary.csv") if (ROOT / "validation_Nr_summary.csv").exists() else None

    plt.figure(figsize=(12, 6))
    for c, dt in zip(dt_cases, dt_list):
        t = arr(c.time) / 3600
        idx = np.arange(1, len(t))
        plt.plot(t[idx], arr(c.Tout)[idx], lw=1.1, label=f"dt = {dt:g} s")
    plt.xlabel("Time / h")
    plt.ylabel("Outlet air temperature / degC")
    plt.grid(True, alpha=0.35)
    plt.legend()
    savefig("numerical_validation", "numerical_validation_01_time_step_independence.png")

    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    if dt_summary is not None:
        axes[0, 0].plot(dt_summary.iloc[:, 0], dt_summary.iloc[:, 1], "o-")
        axes[0, 0].set_xlabel("dt / s")
        axes[0, 0].set_ylabel("RMSE / K")
    if nx_summary is not None:
        axes[0, 1].plot(nx_summary.iloc[:, 0], nx_summary.iloc[:, 1], "o-")
        axes[0, 1].set_xlabel("Nx")
        axes[0, 1].set_ylabel("RMSE / K")
    if nt_summary is not None:
        axes[1, 0].plot(nt_summary.iloc[:, 0], nt_summary.iloc[:, 1], "o-")
        axes[1, 0].set_xlabel("Ntheta")
        axes[1, 0].set_ylabel("RMSE / K")
    if nr_summary is not None:
        axes[1, 1].plot(nr_summary.iloc[:, 0], nr_summary.iloc[:, 1], "o-")
        axes[1, 1].set_xlabel("Nr")
        axes[1, 1].set_ylabel("RMSE / K")
    for ax in axes.ravel():
        ax.grid(True, alpha=0.35)
    savefig("numerical_validation", "numerical_validation_02_grid_independence_summary.png")


def export_summary_workbook():
    csvs = [
        ("degradation_validation_summary.csv", "Degradation", "degradation_validation_result.mat"),
        ("gap_sensitivity_summary.csv", "GapThickness", "gap_sensitivity_result.mat"),
        ("gap_conductivity_sensitivity_summary.csv", "GapConductivity", "gap_conductivity_sensitivity_result.mat"),
        ("operation_mdot_summary.csv", "MassFlow", "operation_sensitivity_result.mat"),
        ("operation_length_summary.csv", "PipeLength", "operation_sensitivity_result.mat"),
        ("soil_layer2_sensitivity_summary.csv", "SoilLayer2", "soil_layer2_sensitivity_result.mat"),
        ("variable_gap_extension_summary.csv", "VariableGapCompare", "variable_gap_extension_result.mat"),
        ("variable_gap_sensitivity_summary.csv", "VariableGapSensitivity", "variable_gap_sensitivity_result.mat"),
        ("validation_dt_summary.csv", "Validation_dt", "numerical_validation_result.mat"),
        ("validation_Nx_summary.csv", "Validation_Nx", "numerical_validation_result.mat"),
        ("validation_Ntheta_summary.csv", "Validation_Ntheta", "numerical_validation_result.mat"),
        ("validation_Nr_summary.csv", "Validation_Nr", "numerical_validation_result.mat"),
    ]
    out = ROOT / "EAHE_summary_tables.xlsx"
    with pd.ExcelWriter(out) as writer:
        wrote = False
        for csv, sheet, mat_name in csvs:
            path = ROOT / csv
            if path.exists() and mat_file_is_current(mat_name):
                pd.read_csv(path).to_excel(writer, sheet_name=sheet, index=False)
                wrote = True
        if not wrote:
            pd.DataFrame({"message": ["No current-revision summary tables available."]}).to_excel(
                writer, sheet_name="Status", index=False
            )


def mat_file_is_current(mat_name: str) -> bool:
    path = ROOT / mat_name
    if not path.exists():
        return False
    try:
        data = loadmat(mat_name)
        if "result" in data:
            return is_current_result(data["result"])
        if "results" in data:
            cases = result_list(data["results"])
            return bool(cases) and is_current_result(cases[0])
        if "case_gap" in data:
            return is_current_result(data["case_gap"])
        if "fixed_case" in data:
            return is_current_result(data["fixed_case"])
        for key in ("m_results", "L_results", "dt_results", "Nx_results", "Ntheta_results", "Nr_results"):
            if key in data:
                cases = result_list(data[key])
                return bool(cases) and is_current_result(cases[0])
    except Exception:
        return False
    return False


def export_key_findings():
    lines = ["EAHE Key Findings", "=================", ""]
    if (ROOT / "baseline_result.mat").exists():
        r = loadmat("baseline_result.mat")["result"]
        if is_current_result(r):
            lines += [
                "Baseline case",
                f"- Final outlet temperature: {float(arr(r.Tout)[-1]):.2f} degC",
                f"- Last-day mean heat transfer: {float(arr(r.degradation.Q_day_mean)[-1]):.1f} W",
                f"- Last-day heat-transfer degradation ratio: {float(arr(r.degradation.eta_Q_day)[-1]):.3f}",
                f"- Last-day near-pipe mean soil temperature rise: {float(arr(r.degradation.near_soil_rise_day_mean)[-1]):.2f} K",
                "",
            ]
        else:
            lines += [
                "Baseline case",
                f"- Skipped: baseline_result.mat revision is {result_revision(r)}, expected {CURRENT_REVISION}.",
                "",
            ]
    csv_to_mat = {
        "degradation_validation_summary.csv": "degradation_validation_result.mat",
        "gap_sensitivity_summary.csv": "gap_sensitivity_result.mat",
        "gap_conductivity_sensitivity_summary.csv": "gap_conductivity_sensitivity_result.mat",
        "operation_mdot_summary.csv": "operation_sensitivity_result.mat",
        "operation_length_summary.csv": "operation_sensitivity_result.mat",
        "soil_layer2_sensitivity_summary.csv": "soil_layer2_sensitivity_result.mat",
        "variable_gap_extension_summary.csv": "variable_gap_extension_result.mat",
        "variable_gap_sensitivity_summary.csv": "variable_gap_sensitivity_result.mat",
        "validation_dt_summary.csv": "numerical_validation_result.mat",
        "validation_Nx_summary.csv": "numerical_validation_result.mat",
        "validation_Ntheta_summary.csv": "numerical_validation_result.mat",
        "validation_Nr_summary.csv": "numerical_validation_result.mat",
    }
    for csv_name, mat_name in csv_to_mat.items():
        csv = ROOT / csv_name
        if not csv.exists():
            continue
        lines.append(csv.name)
        lines.append("-" * len(csv.name))
        if mat_file_is_current(mat_name):
            df = pd.read_csv(csv)
            lines.append(df.to_string(index=False))
        else:
            lines.append(f"Skipped: {mat_name} is missing or not current revision.")
        lines.append("")
    (ROOT / "EAHE_key_findings.txt").write_text("\n".join(lines), encoding="utf-8")


def main():
    FIGROOT.mkdir(exist_ok=True)
    plot_baseline()
    plot_degradation()
    plot_gap_thickness()
    plot_gap_conductivity()
    plot_operation()
    plot_soil_layer2()
    plot_temperature_contours()
    plot_variable_gap_extension()
    plot_variable_gap_sensitivity()
    plot_numerical_validation()
    export_summary_workbook()
    export_key_findings()
    print("Python fallback export complete.")


if __name__ == "__main__":
    main()
