% Regenerate baseline figures from baseline_result.mat using current plotting
% settings. This avoids rerunning the simulation when only figure formatting
% has changed.

clear; clc; close all;

if ~exist('baseline_result.mat', 'file')
    error('baseline_result.mat not found. Run main_baseline first.');
end

load('baseline_result.mat', 'result');
if ~is_current_result(result)
    error('baseline_result.mat was generated by an old model revision. Run generate_all_outputs first.');
end
plot_eahe_summary(result);
save_all_open_figures(fullfile('figures', 'baseline'), 'baseline');

fprintf('Baseline figures regenerated.\n');

function tf = is_current_result(result)
    tf = isfield(result, 'param') ...
        && isfield(result.param, 'model_revision') ...
        && strcmp(result.param.model_revision, 'soil_phase_offset_v2');
end
