% Regenerate variable-gap sensitivity figures from saved MAT data.
% This does not rerun the simulation.

clear; clc; close all;

if ~exist('variable_gap_sensitivity_result.mat', 'file')
    error('variable_gap_sensitivity_result.mat not found. Run main_sensitivity_variable_gap first.');
end

load('variable_gap_sensitivity_result.mat', 'results', 'labels');
if isempty(results) || ~is_current_result(results{1})
    error('variable_gap_sensitivity_result.mat was generated by an old model revision. Run generate_all_outputs first.');
end

nCase = numel(results);

figure('Name', 'Variable gap sensitivity - outlet temperature');
hold on;
for c = 1:nCase
    idx = 2:numel(results{c}.time);
    plot(results{c}.time(idx)/3600, results{c}.Tout(idx), 'LineWidth', 1.2);
end
xlabel('Time / h');
ylabel('Outlet air temperature / degC');
legend(labels, 'Location', 'best');
grid on;

figure('Name', 'Variable gap sensitivity - daily mean heat transfer');
hold on;
for c = 1:nCase
    plot(results{c}.degradation.day, results{c}.degradation.Q_day_mean, ...
        'o-', 'LineWidth', 1.2);
end
xlabel('Operation day');
ylabel('Daily mean heat transfer rate / W');
legend(labels, 'Location', 'best');
grid on;

figure('Name', 'Variable gap sensitivity - gap resistance factor');
hold on;
for c = 1:nCase
    plot(results{c}.time/3600, results{c}.Rgap_factor_mid_mean, 'LineWidth', 1.2);
end
xlabel('Time / h');
ylabel('Mean R_{gap} factor at middle segment');
legend(labels, 'Location', 'best');
grid on;

save_all_open_figures(fullfile('figures', 'variable_gap_sensitivity'), ...
    'variable_gap_sensitivity');

fprintf('Variable-gap sensitivity figures regenerated.\n');

function tf = is_current_result(result)
    tf = isfield(result, 'param') ...
        && isfield(result.param, 'model_revision') ...
        && strcmp(result.param.model_revision, 'soil_phase_offset_v2');
end
